Fix hook description.
aws-cloudformation/aws-cloudformation-samples pull request #52
Opened 2022-06-29 02:09 UTC by LeMikaelF

*Issue #, if available:*

N/A

*Description of changes:*

Fix a hook description. It was a copy/paste from another one, and therefore not correct. I don't know if this will eventually reflect in the CloudFormation public registry, but it would help new users get acquainted with these sample hooks.

A noticed that other hooks also have the same incorrect copy/pasted description, but I didn't have enough time to go through them.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-03-13 15:26 UTC, mrinaudo-aws requested changes
Thank you, @LeMikaelF !  I have requested a change, can you please address it and request again the review?  Thank you, and sorry for delays!

2023-03-13 15:26 UTC, mrinaudo-aws commented on hooks/java-hooks/sqs-policy-non-public/awssamples-sqsnonpublic-hook.json
> +    "description": "Validates that SQS queues are not publicly accessible.",
```suggestion
    "description": "Example hook to verify that SQS queues are not publicly accessible.",
```

2023-03-15 20:29 UTC, mrinaudo-aws approved these changes
lgtm - thank you, @LeMikaelF !

2023-03-15 20:35 UTC, wkexiang approved these changes

2023-03-15 20:35 UTC, merged